pwd=~root/woqu2/python

cleantrash:
	-mv $(pwd)/\#* $(pwd)/delete
	-mv $(pwd)/*~ $(pwd)/delete	
	-mv $(pwd)/log/*/* $(pwd)/delete	
	-mv $(pwd)/log/*.log $(pwd)/delete
cleanupdate:
	-rm -f $(pwd)/files/update/*
cleanfiles:
	-rm -f $ped/files/* 
